#!/bin/bash

exec 2>&1
############# Connect to Database #############################
mysql_ready() {
    mysqladmin ping -h {{bind.database.first.sys.ip}} -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} > /dev/null 2>&1
}

if !(mysql_ready) then
     echo "waiting for mysql ..."
     exit 1
fi

mysql -h {{bind.database.first.sys.ip}} -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -e "create database IF NOT EXISTS {{bind.database.first.cfg.username}}"

mysql -h {{bind.database.first.sys.ip}} -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}}  -D {{bind.database.first.cfg.username}} < {{pkg.path}}/database/schema.sql

# create mysql entry
mkdir {{pkg.path}}/bin
printf "#! /bin/bash\n mysql -h {{bind.database.first.sys.ip}} -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}}" >> {{pkg.path}}/bin/mysql.sh

chmod +x {{pkg.path}}/bin/mysql.sh
chown hab:hab {{pkg.path}}/bin/mysql.sh

############# PROJECT SETUP #############################
echo "Copying source files"
cp -r {{pkg.path}}/static/* {{pkg.svc_data_path}}/.

cp {{pkg.svc_config_path}}/database.conf {{pkg.svc_data_path}}/persistence/conf/persistence-conf.php

chmod +x {{pkg.svc_data_path}}
chown -RL hab:hab {{pkg.svc_data_path}}

############# NGINX SETUP #############################
mkdir -p {{pkg.svc_var_path}}/nginx
chown hab:hab {{pkg.svc_var_path}}

