<?php
// This file generated by Propel 1.5.2 convert-conf target
// from XML runtime conf file /home/lancewf/databaseCreator/mmsn/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'persistence' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=;dbname=sjcmmsn',
        'user' => 'sjcmmsn',
        'password' => 'yDjfS8Ku8SxRf43Y',
      ),
    ),
    'default' => 'persistence',
  ),
  'generator_version' => '1.5.2',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-persistence-conf.php');
return $conf;
